FROM nginx:alpine

# Copy the contents of your local 'html' folder 
# into the default Nginx web root directory (/usr/share/nginx/html)
COPY html/ /usr/share/nginx/html

# The default Nginx port is 80, so we expose it.
EXPOSE 80